name: CI

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: npm ci
      - run: npm run lint
  test:
    name: Node.js ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20, 22]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - run: npm ci
      - run: npm test
