name: Publish

on:
  release:
    types: [published]

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  publish-to-npm:
    name: Publish to npm
    permissions:
      contents: read
      id-token: write
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-to-github-packages:
    name: Publish to GitHub Packages
    permissions:
      contents: read
      id-token: write
      packages: write
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
